MWF.xApplication.Attendance.LP = {
	"title": "ລະບົບການເຂົ້າວຽກ",
	"delete" : "ລົບ",
	"deleteDocumentTitle": "ລຶບການຢືນຢັນ",
	"deleteDocument": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບຂໍ້ມູນນີ້ອອກ?",
	"deleteDocumentOK": "ລຶບສຳເລັດ",
	"createSuccess" : "ສ້າງສຳເລັດແລ້ວ",
	"updateSuccess" : "ອັບເດດສຳເລັດ",
	"inputName" : "ກະລຸນາໃສ່ຊື່",

	"dateFormatMonth": "%Yປີ%mເດືອນ",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%mເດືອນ%dວັນທີ",
	"dateFormat": "db",

	"month" :  "ເດືອນ",
	"today" : "ມື້ນີ້",
	"day" : "ມື້",

	"cancel" : "ຍົກເລີກ",
	"ok" : "ຕົກລົງ",

	"create_cancel_title": "ຍົກເລີກການຢືນຢັນໃໝ່",
	"create_cancel": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກການສ້າງໃໝ່?",

	"normal" : "ການເຂົ້າວຽກ", // ສີຂຽວ, ປົກກະຕິ
	"levelAsked":"ຂໍລາພັກ ຫຼື ອອກໄປວຽກນອກ", // ສີຟ້າ, ຂໍລາ
	"late":"ມາຊ້າ", // ສີສົ້ມ, ຊ້າ
	"lateSelectText": ["","ຊ້າ","ບໍ່ຊ້າ"],
	"leaveEarly":"ອອກກ່ອນ", // ສີສົ້ມ, ອອກໄວ
	"noSign":"ຂາດວຽກ", // ສີບົວ, ບໍ່ໄດ້ເຂົ້າສູ່ລະບົບ
	"appealSuccess" : "ສຳເລັດ",
	"lackOfTime" : "ເລີກກ່ອນ",
	"abNormalDuty" : "ການຍົກເວັ້ນ",
	"truefalseSelectText": ["","ແມ່ນ","ບໍ່"],
	"query": "ສອບຖາມ",
	"wholeDay": "ທຸກມື້",
	"am": "ໂມງເຊົ້າ.",
	"pm": "ໂມງແລງ",

	"statusText": {
		"normal" : "ການເຂົ້າວຽກ", // ສີຂຽວ, ປົກກະຕິ
		"levelAsked":"ລາພັກ", // ສີຟ້າ, ຂໍລາ
		"late":"ມາຊ້າ", // ສີສົ້ມ, ຊ້າ
		"leaveEarly":"ອອກກ່ອນ", // ສີສົ້ມ, ອອກໄວ
		"noSign":"ຂາດວຽກ", // ສີບົວ, ບໍ່ໄດ້ເຂົ້າສູ່ລະບົບ
		"appealSuccess" : "ສຳເລັດ",
		"lackOfTime" : "ເລີກກ່ອນ",
		"abNormalDuty" : "ຍົກເວັ້ນ",


		"lateTimes" : "ມາຊ້າ",
		"leaveEarlyTimes" : "ອອກກ່ອນ",
		"lackOfTimeCount" : "ເລີກກ່ອນ",
		"abNormalDutyCount" : "ຂໍ້ຍົກເວັ້ນ",
		"resultNormal" : "ປົກກະຕິ",
		"seriousLateTimes": "ຊ້າເກີນກຳນົດ",
		"outsideDutyTimes": "ນອກພື້ນທີ່",
		"absenteeismTimes": "ຂາດວຽກ",
		"notSignedCount": "ບັດເສຍ",
	},

	"absent" : "ຂາດ",
	"notAbsent" : "ເຂົ້າວຽກ",
	"absendSelectText": ["","ຂາດ","ມາ"],

	"attendanceStatisic" : "ສະຖິຕິການເຂົ້າວຽກ",
	"name" : "ຊື່",
	"onDutyTimes" : "ຈຳນວນເຂົ້າວຽກ",
	"offDutyTimes" : ""ຈໍານວນເລີກວຽກ",
	"onDutyDayCount" : "ຈໍານວນມື້ຄົນເຂົ້າວຽກ",
	"onSelfHolidayCount" : "ຈໍານວນມື້ເຮັດວຽກນອກ",
	"absenceDayCount" : "ຈໍານວນມື້ຄົນຂາດວຽກ",
	"lateTimes" : "ຈໍານວນມາຊ້າ",
	"leaveEarlyTimes" : "ຈຳນວນອອກໄວ",
	"lackOfTimeCount" : "ຈຳນວນເຮັດວຽກບໍ່ຄົບຊົ່ວໂມງ",
	"abNormalDutyCount" : "ເວລາຕອກບັດຜິດປົກກະຕິ",
	"resultNormal" : "ຈໍານວນຄົນຕອກບັດ",
	"seriousLateTimes": "ຈຳນວນມາຊ້າເກີນກຳນົດ",
	"outsideDutyTimes": "ຈຳນວນຕອກບັດນອກພື້ນທີ່",
	"absenteeismTimes": "ຈຳນວນຄົນຂາດ",
	"notSignedCount": "ຈຳນວນຄົນບໍ່ໄດ້ຕອກບັດ",

	"topUnitAttendanceDetail" : "ລາຍລະອຽດການເຂົ້າວຽກ",
	"topUnitAttendanceStatic" : "ສະຖິຕິການເຂົ້າວຽກ",
	"unitAttendanceDetail":"ລາຍລະອຽດການເຂົ້າວຽກຂອງພະແນກ",
	"unitAttendanceStatic":"ສະຖິຕິການເຂົ້າວຽກຂອງພະແນກ",
	"personAttendanceDetail": "ລາຍລະອຽດການເຂົ້າວຽກສ່ວນຕົວ",
	"personAttendanceStatic" : "ສະຖິຕິການເຂົ້າວຽກສ່ວນຕົວ",
	"unitSigninDetail": "ລາຍລະອຽດການເຂົ້າວຽກ",
	"unitSigninStatic": "ສະຖິຕິການເຂົ້າວຽກ",
	"personSigninDetail": "ລາຍລະອຽດການເຂົ້າວຽກສ່ວນຕົວ",
	"personSigninStatic": "ສະຖິຕິການເຂົ້າວຽກສ່ວນຕົວ",
	"staticByDay" : "ສະຖິຕິລາຍວັນ",
	"staticByMonth" : "ສະຖິຕິລາຍເດືອນ",
	"type": "ປະເພດ",
	"topUnit" : "ບໍລິສັດ",
	"unit" : "ພະແນກ",,
	"annuaal" : "ປະຈໍາປີ",
	"months" : "ເດືອນ",
	"date": "ວັນທີ",
	"seeSchedule" : "ເບິ່ງຕາຕະລາງ",
	"unfindSchedule" : "ບໍ່ພົບການກຳນົດກນສຳລັບພະແນກແລະບໍລິສັດ",
	"scheduleTable" : "ຕາຕະລາງກຳນົດເວລາ",
	"signTime" : "ເວລາຕອກບັດ",
	"appeal" : "ຂໍຮ້ອງ",
	"createAppeal": "ຂໍຮ້ອງ",
	"viewAppealDetail": "ເບິ່ງລາຍລະອຽດການຂໍຮ້ອງ",
	"export" : "ສົ່ງອອກ",
	"name1": "ຊື່",
	"alias" : "ນາມແຝງ",
	"range": "ຂອບເຂດ",
	"meter": "ແມັດ",
	"description" : "ລາຍລະອຽດ",
	"save": "ບັນທຶກ",
	"enableMove": "ອະນຸຍາດໃຫ້ຍ້າຍ",
	"workPlaceEmptyNotice": "ບ່ອນເຮັດວຽກບໍ່ສາມາດຫວ່າງເປົ່າໄດ້",
	"BaiduDeveloperCertification": "ການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu",
	"registerBiaduNotice": "ການຕັ້ງຄ່າບ່ອນເຮັດວຽກໃຊ້ບໍລິການຂອງ Baidu Maps ເປີດແມ່ແບບ. ທ່ານສາມາດລົງທະບຽນການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu ເພື່ອເພີ່ມຄວາມສອດຄ່ອງຂອງແຜນທີ່ໄດ້. ຫຼັງຈາກທີ່ການຢັ້ງຢືນສໍາເລັດແລ້ວ, ກະລຸນາຕື່ມຂໍ້ມູນໃສ່ໃນປ່ອງປ້ອນຂໍ້ມູນຂ້າງລຸ່ມນີ້. ",
	"openRegisterUrl": "ກົດທີ່ນີ້ເພື່ອເປີດຊ່ອງທາງການພິສູດຢືນຢັນ",
	"secretKey": "key",
	"mustSelectMonth": "ເຈົ້າຕ້ອງເລືອກວັນທີ, ເລືອກເດືອນໃນເວລາດຽວກັນ",

	"index" : {
		"attendanceCalendar":"ປະຕິທິນການເຂົ້າວຽກ",
		"pieChart" : "ສະຫຼຸບການເຂົ້າວຽກ",
		"lineChart" : "ແນວໂນ້ມການເຂົ້າອອກວຽກ",
		"absent":"ຂໍຂາດ",
		"offDutyTime":"ການເຂົ້າວຽກ, ເວລາກົດບັດ:",
		"levelAsked":"ຂໍລາພັກຫຼືອອກວຽກນອກ"
	},

	"schedule" : {
		"inputVaild" : "ຫົວໜ່ວຍ, ໂມງເຂົ້າວຽກ, ໂມງອອກວຽກ, ໂມງມາຊ້າ, ແລະເວລາຂາດວຽກບໍ່ສາມາດຫວ່າງເປົ່າໄດ້",
		"setSchedule" : "ຕັ້ງຕາຕະລາງ",
		"unit" : "ຫົວຫນ່ວຍ",
		"workTime" : "ເວລາເຮັດວຽກ",
		"offTime" : "ເວລາເລີກວຽກ",
		"lateTime":"ເວລາມາຊ້າ",

		"leaveEarlyTime":"ເວລາມາຊ້າ",
		"absenteeismTime":"ເວລາຂາດວຽກ",
		"illegal":{
			"1":["ເວລາເລີກວຽກບໍ່ສາມາດໄວກວ່າເວລາເຂົ້າວຽກ"],
			"2":["ເວລາພັກຜ່ອນທ່ຽງບໍ່ຄວນໄວກວ່າເວລາເຂົ້າວຽກ","ເວລາສິ້ນສຸດຂອງການພັກທ່ຽງບໍ່ຄວນໄວກວ່າເວລາເລີ່ມຕົ້ນຂອງການພັກທ່ຽງ","ເວລາເລີກວຽກບໍ່ຄວນໄວກວ່າເວລາສິ້ນສຸດຂອງອາຫານທ່ຽງ"],		"3":["ເວລາອອກຕອນເຊົ້າຈະບໍ່ໄວກວ່າເວລາເຂົ້າວຽກ","ເວລາເຂົ້າວຽກໃນຕອນບ່າຍຈະບໍ່ໄວກວ່າໂມງເລີກວຽກຕອນສວຍ","ເວລາເລີກວຽກຈະບໍ່ໄວກວ່າເວລາເຂົ້າວຽກຕອນບ່າຍ"]
		},
		"lateStartTime":"ເວລາເຂົ້າວຽກຊ້າຕອນເຊົ້າ",
		"leaveEarlyStartTime":"ອອກກ່ອນໂມງຕອນສວຍ",
		"leaveEarlyStartTimeMorning":"ເວລາອອກກ່ອນໂມງຕອນສວຍ",
		"lateStartTimeAfternoon":"ເວລາເຂົ້າວຽກຕອນສວຍຊ້າ",
		"signProxy":{
			"name":"ຕັ້ງຄ່າການເຂົ້າວຽກ",
			"select":{
				"1":"ໂມງເຂົ້າສອງຄັ້ງ (ເຮັດວຽກຕອນເຊົ້າ, ອອກງານຕອນບ່າຍ)",
				"2":"ເຂົ້າວຽກສາມຄັ້ງ (ໄປວຽກຕອນເຊົ້າ, ເລີກວຽກຕອນບ່າຍ ແລະ ທ່ຽງ, ລວມສາມເທື່ອ)",
				"3":"ເຂົ້າວຽກສີ່ຄັ້ງ (ເຊົ້າ,ສວຍ2ຄັ້ງ,ແລງ)"
			},
			"2":{
				"middayRestStartTime":"ເວລາເຂົ້າວຽກຕອນບ່າຍ",
				"middayRestEndTime":"ເວລາສິ້ນສຸດພັກຜ່ອນທ່ຽງ",
			},
			"3":{
				"middayRestStartTime":"ເລີກວຽກຕອນເຊົ້າ",
				"middayRestEndTime":"ເວລາເຂົ້າວຽກຕອນບ່າຍ",
			}
		}
		//"" : "打卡有效时间",
		//"" : "从",
		//"" : "到",
		//"" : "旷工",
		//"" : "上班缺勤",
		//"" : "下班缺勤",
		//"" : "上下班均缺勤"
	},
	"holiday" : {
		"inputValid" : "ປີ, ຊື່ວັນພັກ, ເລີ່ມເວລາ, ເວລາສິ້ນສຸດ, ກະລຸນາຕື່ມຂໍ້ມູນໃສ່!",
		"setHoliday" : "ການກຳນົດວັນພັກຕາມກົດໝາຍແຮງງານ",
		"year" : "ປີ",
		"name" : "ຊື່ວັນພັກ",
		"startDate" : "ວັນທີເລີ່ມຕົ້ນ",
		"endDate" : "ວັນສິ້ນສຸດ",
		"makeUpClassDay" : "ໝາຍເວລາເຂົ້າວຽກ",
		"holidaySchedule" : "ຕາຕະລາງວັນພັກ",
		"addMakeUpClassDay": "ເພີ່ມເວລາເຂົ້າວຽກ",
		"beginGreateThanEndNotice": "ວັນທີເລີ່ມບໍ່ສາມາດຫຼາຍກວ່າວັນທີສິ້ນສຸດ"
	},
	"permission" : {
		"setAttendancer" : "ການຕັ້ງເຂົ້າວຽກພະນັກງານ",
		"role" : "ບົດບາດ",
		"personName" : "ພະນັກງານ",
		"unit" : "ຫນ່ວຍ",
		"roleSelectText": ["ຜູ້ບໍລິຫານບໍລິສັດ","ຜູ້ດູແລພະແນກ"]
	},
	"selfHoliday" : {
		"inputValid" : "ພະແນກ, ຊື່ພະນັກງານ, ປະເພດວັນພັກ, ເວລາເລີ່ມ, ເວລາສິ້ນສຸດ, ແລະຈໍານວນວັນພັກ, ກະລຸນາຕື່ມຂໍ້ມູນໃສ່!"
	},
	"nextActivity": "ການເຄື່ອນໄຫວຕໍ່ໄປ:",
	"nextUser": "ຄົນປະມວນຜົນ:",
	"deal": "ປະມວນຜົນ",
	"processStarted": "ເລີ່ມໄຟລ໌",
	"processStartedMessage": "ເຈົ້າເລີ່ມວຽກໃໝ່:",

	"auditStatus" : "ສະຖານະອະນຸມັດ",
	"auditStatusSelectText" : ["ສະຖານະທັງໝົດ","ລໍຖ້າ","ອະນຸມັດຜ່ານ","ອະນຸມັດບໍ່ສໍາເລັດ"],
	"appealReason": "ເຫດຜົນ",
	"appealReasonSelectText" : ["","ເວລາລາພັກ","ອອກຕ່າງແຂວງ","ອອກວຽກນອກ","ອື່ນໆ"],
	"department": "ພະແນກ",
	"person" : "ພະນັກງານ",
	"auditor": "ຜູ້ກວດສອບ"
	"search": "ຄົ້ນຫາ",
	"selectPerson": "ເລືອກພະນັກງານ",
	"selectCompany": "ເລືອກບໍລິສັດ",
	"selectDepartment": "ເລືອກພະແນກ",
	"selectAppealNotice": "ກະລຸນາເລືອກການຂໍຮ້ອງກ່ອນ",
	"agreeAppealConfirmTitle":  "ຕົກລົງທີ່ຈະຂໍຮ້ອງ",
	"agreeAppealConfirmContent": "ທ່ານແນ່ໃຈບໍ່ທີ່ຈະດໍາເນີນ {count} ການອຸທອນທີ່ທ່ານເລືອກ?",
	"actionSuccess": "ການປະມວນຜົນສຳເລັດ",
	"disagreeAppealConfirmTitle": "ບໍ່ເຫັນດີກັບການຂໍຮ້ອງ",
	"disagreeAppealConfirmContent": "ທ່ານແນ່ໃຈບໍ່ທີ່ຈະດໍາເນີນ {count} ການອຸທອນທີ່ທ່ານເລືອກ?",
	"draft": "ເລີ່ມ",
	"todo": "ລໍຖ້າດຳເນີນ",
	"approve": "ອະນຸມັດແລ້ວ",
	"deny": "ອະນຸມັດບໍ່ຜ່ານ",
	"apealApplyForm": "ແບບຟອມຄຳຮ້ອງ",
	"apealForm": "ຟອມຄຳຮ້ອງ",
	"employeeName": "ຊື່ພະນັກງານ",
	"recordDate": "ວັນທີເຂົ້າວຽກ",
	"onDutyTime": "ເວລາກົດບັດເຂົ້າວຽກ",
	"offDutyTime": "ເວລາກົດບັດເລີກວຽກ",
	"attendanceStatus": "ສະຖານະເຂົ້າວຽກ",
	"appealStatus": "ສະຖານະອະນຸມັດ",
	"appealStatusSelectText": ["ກໍາລັງດໍາເນີນ","ບໍ່ຜ່ານ","ຜ່ານ"],
	"address": "ສະຖານທີ່",
	"leaveType": "ປະເພດລາພັກ",
	"leaveTypeSelectText": ["","​ພັກ​ປະ​ຈໍາ​ປີ​","ລາປ່ວຍ","ສະຫວັດດີການ","ລາວຽກສ່ວນຕົວ(ຕັດເງິນ)","ອື່ນໆ"],
	"startTime": "ເລີ່ມວັນທີ່",
	"endTime": "ສິ້ນສຸດວັນທີ່",
	"appealDescriptoin": "ເຫດຜົນ",
	"close": "ປິດ",
	"disagree": "ບໍ່ເຫັນດີ",
	"agree": "ຕົກລົງ",
	"batchDisagree": "ບໍ່ເຫັນດີທັງໝົດ",
	"batchAgree": "ເຫັນດ້ວຍທັງໝົດ",
	"temporaryLeave": "ລາພັກຊົ່ວຄາວ",
	"out": "ອອກຕ່າງແຂວງ"
	"businessTrip": "ອອກວຽກນອກ",
	"other": "ອື່ນໆ",
	"inputIdeaNotice": "ກະລຸນາຕື່ມຄວາມຄິດເຫັນຂອງເຈົ້າ",
	"processSuccess": "ການປະມວນຜົນສຳເລັດ",
	"noDepartment": "ບໍ່ພົບພະແນກຂອງເຈົ້າ, ກະລຸນາຕິດຕໍ່ຜູ້ບໍລິຫານ!",
	"signinType": "ປະເພດການເຂົ້າສູ່ລະບົບ",
	"signinTypeSelectText": ["", "ກົດບັດເຮັດວຽກ", "ກົດບັດເລີກວຽກ"],
	"signinQywxTypeSelectText": ["", "ກົດບັດເຂົ້າວຽກ”, "ກົດບັດເລີກວຽກ"", "ກົດບັດອອກວຽກນອກ"],
	"signinResult": "ຜົນການເຂົ້າວຽກ",
	"signinResultSelectText": ["", "ປົກກະຕິ", "ອອກກ່ອນໂມງ", "ຊ້າ", "ຊ້າເກີນກຳນົດ", "ຊ້າກາຍເວລາ", "ບໍ່ກົດບັດ"],
	"signinQywxResultSelectText": ["", "ປົກກະຕິ", "ເວລາຜິດ", "ສະຖານທີຜິດ", "ບໍ່ກົດບັດ" , "wifiລົ້ມ", "ບໍ່ໄດ້ໃຊ້ລະບົບດົນ"],
	"recordAddress": "ສະຖານທີກົດບັດ",
	"optMachineType": "ລະບົບຂໍ້ຄວາມ",
	"workTime": "ເວລາເຂົ້າວຽກ,

	"systemSetting" : "ຕັ້ງຄ່າລະບົບ",
	"reportTo": "ລາຍງານ",
	"appealEnable": "ສະຖານະໃຊ້ງານ",
	"appealSelectText": ["ເປີດ","ປິດ"],
	"appealAuditFlowType": "ປະເພດຂະບວນການຂໍຮ້ອງເຂົ້າວຽກ",
	"appealAuditFlowTypeSelectText": ["ກຳນົດເອງ","ລະບົບກຳນົດ"],
	"appealAuditor": "ຄົນກວດສອບຄຳຮ້ອງ",
	"appealAuditorType": "ວິທີ",
	"appealAuditorValue": "ເນື້ອໃນ",
	"directSupervisor": "ຫົວໜ້າພະແນກ",
	"appealAuditFlow" : "ກຳນົດເອງ",
	"none": "ບໍ່ມີ",
	"saveSuccess": "ບັນທຶກສຳເລັດ",
	"noReportToNotice": "ລາຍງານຂອງທ່ານບໍ່ໄດ້ຖືກຕັ້ງຄ່າໃນການຈັດການອົງກອນ，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ",
	"unitDuty": "ຕໍາແໜ່ງພະແນກ",
	"noUnitDutyNotice": "ບໍ່ມີຕຳແໜ່ງ{duty}ຂອງ{unit}ຖືກຕັ້ງຄ່າ，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ",
	"personAttribute": "ຄຸນລັກສະນະພະນັກງານ",
	"noPersonAttribute": "ພະນັກງານບໍ່ໄດ້ຮັບການຕັ້ງຄ່າ“{att}”，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ",
	"assignedPerson": "ຜູ້ຖືກມອບໝາຍ",
	"directLeader": "ຜູ້ຄອບຄຸມ",
	"noDirectLeader": "ພະນັກງານບໍ່ໄດ້ຮັບການຕັ້ງຄ່າ“ຜູ້ຄອບຄຸມ”，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ",
	"createAppealNotice": "ຄຳຮ້ອງສົ່ງແລ້ວ",

	"offDutyAbbrev": "ປິດ",
	"onDutyAbbrev": "ເປີດ",
	"attendanceSummary": "ສະຫຼຸບການເຂົ້າວຽກ",
	"attendanceTrendChart": "ຜັງການເຂົ້າອອກວຽກ",
	"trendChartLegend" : ['ເວລາເຂົ້າວຽກ', 'ເວລາອອກວຽກ'],
	"attendanceTrend": "ແນວໂນ້ມເຂົ້າວຽກ",
	"year": "ປີ",

	"importExcelNotice": "ກະລຸນານຳເຂົ້າexcel！",
	"analyseDataSuccess": "ວິເຄາະຂໍ້ມູນເຮັດວຽກສຳເລັດ",
	"statDataSuccess": "ສະຖິຕິຂໍ້ມູນເຮັດວຽກສຳເລັດ",
	"importDataStep": "ຂັ້ນຕອນນຳເຂົ້າຂໍ້ມູນ",
	"importStepDescription": [
		"1、ດາວໂຫຼດຮູບແບບExcel，ຕາມລັກສະນະຮູບແບບຂໍ້ມູນເຂົ້າວຽກ；",
		"2、ກົດປູ່ມນຳເຂົ້າຂໍ້ມູນການເຮັດວຽກ，ຢືນຢັນເລືອກຂໍ້ມູນການເຮັດວຽກ，ລະບົບຈະກວດສອບຂໍ້ມູນການບັນທຶກການມາວຽກວ່າຖືກຕ້ອງຫຼືບໍ່ແລະອັບໂຫຼດຂໍ້ມູນເຂົ້າ；",
		"3、ກົດປຸ່ມບັນທຶກຂໍ້ມູນການມາວຽກ，ເລືອກປີແລະເດືອນທີ່ຕ້ອງການກວດສອບ，ລະບົບຈະດຳເນີນການກວດສອບຂໍ້ມູນຂອງພະນັກງານທີ່ຕ້ອງການຢາກກວດສອບ；" ,
		"4、ກົດປຸ່ມວິເຄາະຂໍ້ມູນການບັນທຶກການມາວຽກ，ລະບົບຈະສ້າງລາຍລະອຽດຂໍ້ມູນການຂາດວຽກ；" ,
		"5、ກົດປຸ່ມວິເຄາະຂໍ້ມູນການບັນທຶກການມາວຽກ，ລະບົບຈະສ້າງການສະຫຼຸບອັດຕາການຂາດວຽກຂອງສ່ວນບຸກຄົນ、ພະແນກ、ບໍລິສັດ。"
	],
	"selectCheckMonth":"ເລືອກກວດສອບລາຍເດືອນ",
	"checkDetailSuccess": "ກວດສອບຂໍ້ມູນເຂົ້າວຽກສຳເລັດ",
	"importDataResult":"ຜົນນຳເຂົ້າຂໍ້ມູນເຂົ້າວຽກ",
	"importDataResultSuccess": "ເອກະສານທີ່ທ່ານອັບໂຫຼດ:“{fileName}”ນຳເຂົ້າຂໍ້ມູນສຳເລັດ。ສະແດງ{count}ລາຍການ：",
	"importDataResultFail": "ເອກະສານທີ່ທ່ານອັບໂຫຼດ:“{fileName}”ບໍ່ຜ່ານການກວດສອບ，ມີ{errorCount}ລາຍການຂໍ້ມູນຜິດພາດ。ກະລຸນາແກ້ໄຂຫຼັງຈາກນຳເຂົ້າໃໝ່。ສະແດງ{count}ລາຍການ：",
	"importDataResultThList" : [
		"ລຳດັບ", "IDພະນັກງານ", "ຊື່", "ວັນທີ","ເວລາເຂົ້າວຽກຕອນເຊົ້າ","ເວລາເລີກວຽກຕອນສວຍ","ເວລາເຂົ້າວຽກສວຍ","ເວລາເລີກວຽກແລງ","ຜົນກວດສອບ","ອະທິບາຍ"
	],
	"selectExportMonth":"ເລືອກນຳອອກຂໍ້ມູນລາຍເດືອນ",
	"exportSourceData": "ນຳອອກຂໍ້ມູນກົດບັດ",
	"true": "ຖືກ",
	"false": "ຜິດ",
	"checkDataTitle": "ກຳລັງກວດສອບຂໍ້ມູນ",
	"checkDataContent": "ເລີ່ມກວດສອບຂໍ້ມູນ，ທັງໝົດ{count}ລາຍການ",
	"importDataTitle": "ກຳລັງນຳເຂົ້າຂໍ້ມູນ",
	"importDataContent": "ເລີ່ມນຳເຂົ້າຂໍ້ມູນ，ທັງໝົດ{count}ລາຍການ",
	"readyToImportData": "ກຳລັງກຽມນຳເຂົ້າຂໍ້ມູນ",
	"readyToImportData1": "ກຳລັງກຽມນຳເຂົ້າຂໍ້ມູນ...",
	"importSpeed": "ລາຍການ/ວິ",
	"checkingDataContent": "ກຳລັງກວດສອບຂໍ້ມູນ: {speed}ລາຍການ/ວິ,ທັງໝົດ{total}ລາຍການ,ຍັງເຫຼືອ{remaining}ລາຍການ",
	"checkingDataErrorContent": ",ຜິດພາດ{errorCount}ລາຍການ",
	"importingDataContent": "ກຳລັງນຳເຂົ້າຂໍ້ມູນ: {speed}ລາຍການ/ວິ,ທັງໝົດ{total}ລາຍການ,ຍັງເຫຼືອ{remaining}ລາຍການ",
	"importingDataErrorContent": ",ພິດພາດ{errorCount}ລາຍການ",
	"hour":"ຊົ່ວໂມງ",
	"mintue": "ນາທີ",
	"second": "ວິນາທີ",
	"importSuccessTitle": "ນຳເຂົ້າສຳເລັດ",
	"importSuccessContent": "ນຳເຂົ້າຂໍ້ມູນທັງໝົດ{total}ລາຍການ  ຄວາມໄວ: {speed}ລາຍການ/ວິ  ໃຊ້ເວລາ: {timeStr}",
	"importFailTitle": "ນຳເຂົ້າລົ້ມເລ້ວ",
	"importFailContent": "ຂໍ້ມູນທັງໝົດ{total}ລາຍການ  ຜິດພາດ: {errorCount}ລາຍການ  ໃຊ້ເວລາ: {timeStr} ກະລຸນາດັດແກ້ຫຼັງນຳເຂົ້າຂໍ້ມູນ",

	"myDetail": "ລາຍລະອຽດເຂົ້າວຽກຂອງຂ້ອຍ",
	"myDetailStatic": "ສະຖິຕິເຂົ້າວຽກຂອງຂ້ອຍ",

	"cyclText" : "ມື້ເຂົ້າອອກວຽກ：{start}-{end}",

	"personSetting": "ຕັ້ງຄ່າພະນັກງານເຂົ້າອອກວຽກ",
	"configType": "ປະເພດຕັ້ງຄ່າ",
	"configTypeSelectText": ["ຈຳເປັນ","ບໍ່ຈຳເປັນ"],
	"topUnitName": "ຊື່ບໍລິສັດ",
	"unitName": "ຊື່ພະແນກ",
	"employeeNumber":"IDພະນັກງານ",
	"joininDate": "ມື້ເລີ່ມເຂົ້າວຽກ",

	"exportEmployeeHolidayRecord": "ນຳອອກບັນທຶກພະນັກງານລາພັກ",
	"employeeHolidayRecord": "ບັນທຶກພະນັກງານລາພັກ",

	"leaveType1": "ປະເພດມື້ພັກ",
	"leaveTypeSelectText1" : ["ພັກປະຈຳປີ","ລາປ່ວຍ","ສະຫວັດດີການ","ລາວຽກສ່ວນຕົວ(ຕັດເງິນ)","ອື່ນໆ"],
	"leaveDayCount": "ຈຳນວນມື້ພັກ",

	"statisticsPeriodSetting": "ຕັ້ງຄ່າໄລຍະເວລາສະຖິຕິ",
	"selectCompanyNotice": "ກົດສອງຄັ້ງເພື່ອເລືອກ，ຂຽນ'*'ເພື່ອໃຫ້ກົງກັບບໍລິສັດທັງໝົດ",
	"selectDepartmentNotice": "ກົດສອງຄັ້ງເພື່ອເລືອກ，ຂຽນ'*'ເພື່ອໃຫ້ກົງກັບທຸກພະແນກ",
	"statisticsCompany": "ສະຖິຕິບໍລິສັດ",
	"statisticsUnit": "ສະຖິຕິພະແນກ",
	"cycleYear": "ສະຖິຕິລາຍປີ",
	"cycleMonth":"ສະຖິຕິລາຍເດືອນ",
	"startDate": "ມື້ເລີ່ມ",
	"endData": "ມື້ສິ້ນສຸດ",

	"selectStartEndEndDataNotice":"ກະລຸນາເລືອກວັນເລີ່ມແລະວັນສິ້ນສຸດ",
	"weekendSetting": "ຕັ້ງຄ່າທ້າຍອາທິດ",
	"selectWeekend": "ເລືອກທ້າຍອາທິດ",

	"detail": "ອະທິບາຍ",
	"appealDate": "ມື້ຮ້ອງຂໍ",
	"auditOpinion": "ອະນຸມັດຄຳເຫັນ",

	"holiday1": "ມື້ພັກເທດສະການ",
	"weekend": "ທ້າຍອາທິດ",
	"workDaysoff": "ພັກຊົດຊີຍ",
	"workDay": "ມື້ເຮັດວຽກ",

	"middayRestStartTime":"ເວລາເລີ່ມພັກທ່ຽງ",
	"middayRestEndTime":"ເວລາສິ້ນສຸດພັກທ່ຽງ",
	"isCheckInOutOfRange": "ຂອບເຂດກົດບັດນອກ",
	"yes": "ແມ່ນ",
	"no": "ບໍ່",

	"createWorkLocation":"ສະຖານທີ່ເຮັດວຽກໃໝ່",
	"createWorkLocationText": "ກົດແລະຍ້າຍໄປທີ່ທີ່ສອດຄ້ອງກັນໃນແຜນທີ່ ແລະກົດອີກຄັ້ງເພື່ອສ້າງ",
	"setBaiduDeveloperCertification": "ຕັ້ງການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu",
	"setBaiduDeveloperCertificationText": "ການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu ແມ່ນຈໍາເປັນເພື່ອຕັ້ງຄ່າບ່ອນເຮັດວຽກ",

	"action": "ດຳເນີນການ",
	"start": "ເວລາເລີ່ມ",
	"end": "ເວລາສິ້ນສຸດ",

	"appealIsDisable": "ອະນຸມັດຄຳຮ້ອງເຂົ້າອອກວຽກຖືກຢຸດການໃຊ້ງານ",
	"batchDeal": "ປະມວນຜົນທັງໝົດ：",
	"holi": "ວັນພັກ",
	"work": "ເຮົ້າວຽກທົດແທນ",
	"newHoliday": "ຕັ້ງຄ່າວັນພັກໃໝ່",
	"onDutyDayCount1": "ຈຳນວນມື້ເຂົ້າວຽກ",
	"onSelfHolidayCount1":"ຂຳນວນວັນພັກຫຼືອອກວຽກນອກ",
	"absentCount": "ຂຳນວນມື້ຂາດ",

	"fileName": "ຊື່ເອກະສານ",
	"fileSize": "ຂະໜາດເອກະສານ",
	"uploadTime": "ເວລາອັບໂຫຼດ",
	"uploadPerson": "ອັບໂຫຼດຄົນ",
	"action": "ດຳເນີນການ",
	"deleteFile": "ລົບເອກະສານ",
	"download": "ດາວໂຫຼດເອກະສານ",
	"viewImportResult": "ເບິ່ງຜົນການອັບໂຫຼດ",
	"downloadExcelTemplate": "ດາວໂຫຼດຟອມExcel",
	"imporData": "ອັບໂຫຼດຂໍ້ມູນບັນທຶກການມາວຽກ",
	"checkData": "ກວດສອບຂໍ້ມູນບັນທຶກການມາວຽກ",
	"statData": "ລວບລວມຂໍ້ມູນບັນທຶກການມາວຽກ",
	"analyzeData": "ວິເຄາະຂໍ້ມູນບັນທຶກການມາວຽກ",
	"viewDescription": "ເບິ່ງຄຳອະທິບາຍ",
	//"myAppealTitleText": "ກະລຸນາເລືອກ“ສະລຸບຂໍ້ມູນບັນທຶກການມາວຽກຂອງຂ້ອຍ -> ລາຍລະອຽດຂາດວຽກຂອງຂ້ອຍ”ສະແດງເຫດຜົນ"
	"myAppealTitleText": "ກະລຸນາເລືອກສະລຸບຂໍ້ມູນບັນທຶກການມາວຽກຂອງຂ້ອຍ",

	"createManager": "ສ້າງຜູ້ດູແລ",
	"createPersonConfig": "ເພີ່ມລາຍຊື່ພະນັກງານເຂົ້າການ",
	"addStaticCycle": "ເພີ່ມການສະລຸບຊ່ວງເວລາ",
	"errorDescription": "ຄຳອະທິບາຍຜິດ",
	"createSchedule": "ຕັ້ງຄ່າຕາຈະລາງໃໝ່",
	"deleteSelected": "ລົບເອກະສານທີ່ເລືອກ",

	"navi": {
		"myIndex": "ລາຍງານການບັນທຶກມາວຽກຂອງຂ້ອຍລາຍເດືອນ",
		"myDetail": "ສະລຸບຂໍ້ມູນບັນທຶກການມາວຽກຂອງຂ້ອຍ",
		"myAppealDeal": "ຄຳຮ້ອງຂອງຂ້ອຍ",
		"appealDeal": "ອະນຸມັດຄຳຮ້ອງພະນັກງານເຂົ້າອອກວຽກ",

		"unitIndex": "ລາຍງານການບັນທຶກມາວຽກພະແນກລາຍເດືອນ",
		"peopleDetail": "ລາຍງານການບັນທຶກມາວຽກສ່ວນບຸກຄົນ",
		"unitDetail": "ສະລຸບການບັນທຶກມາວຽກພະແນກ",
		"topUnitDetail": "ສະລຸບການບັນທຶກມາວຽກໃນບໍລິສັດ",
		"unitDingdingIndex": "ບັນທຶກມາວຽກແອັບຕິງຕິງລາຍເດືອນ",
		"unitQywxIndex": "ບັນທຶກມາວຽກໃນwechatລາຍເດືອນ",
		"dingdingPeopleDetail": "ບັນທຶກມາວຽກສ່ວນບຸກຕົນໃນແອັບຕິງຕິງລາຍເດືອນ",
		"dingdingUnitDetail": "ບັນທຶກມາວຽກແອັບຕິງຕິງ",
		"qywxPeopleDetail": "ບັນທຶກມາວຽກສ່ວນບຸກຕົນໃນwechat",
		"qywxUnitDetail": "ບັນທຶກມາວຽກໃນwechat",

		"maintain": "ບໍາລຸງຮັກສາ",
		"importing": "ຂໍ້ມູນນຳເຂົ້າ",
		"importedInvalidInfor": "ເຂົ້າເຖິງຂໍ້ມູນຜິດພາດ",
		"abnormalExport": "ນຳອອກຂໍ້ມູນເຂົ້າວຽກຜິດປົກກະຕິ",
		"selfHoliday": "ບັນທຶກພະນັກງານລາພັກ",
		"authorization": "ອະນຸຍາດແລະພະນັກງານ",
		"permissionSetting": "ຕັ້ງຄ່າຄົນຈັດການ",
		"personSetting": "ຕັ້ງຄ່າຄົນເຂົ້າອອກວຽກ",
		"config": "ຕັ້ງຄ່າ",
		"scheduleSetting": "ການຕັ້ງຄ່າຕາຕະລາງ",
		"staticsCycleExplorer": "ຕັ້ງຄ່າໄລຍະເວລາສະຖິຕິ",
		"holidaySetting": "ວັນພັກຜ່ອນຕາມກົດໝາຍ",
		"addressSetting": "ການຕັ້ງຄ່າບ່ອນເຮັດວຽກ",
		"appSetting": "ຕັ້ງຄ່າຂໍຮ້ອງ",
		"weekendSetting": "ຕັເງຄ່າທ້າຍອາທິດ",
	},

	"week": "ອາທິດ",
	"weeks": {
		"Sun": "ອາທິດ",
		"Mon": "ຈັນ",
		"Tues": "ຄານ",
		"Wed": "ພຸດ",
		"Thur": "ພະຫັດ",
		"Fri": "ສຸກ",
		"Sat": "ເສົາ",
		"arr": ["ອາທິດ", "ຈັນ", "ຄານ", "ພຸດ", "ພະຫັດ", "ສຸກ", "ເສົາ"]
	}




};